### PR TITLE
Update get-started.md

### PR DESCRIPTION
**Pull request by josegarciamanez**

### CODE REVIEW

**Comment by josegarciamanez** [comment]
pienso que podría quedar mejor así

**Comment by jonniebigodes** [comment]
@josegarciamanez we appreciate the time and effort you put into this small pull request. But with this, I would like to ask you something. Are you willing to update the Spanish translation of the tutorial? As it's in dire need of some updates. If you're ok with it, then please submit a pull request with the full translation and we'll get a proofreader to get it across. 

Let me know and we'll go from there.

Stay safe

**Comment by josegarciamanez** [comment]
Hello @jonniebigodes, I'd be interested in updating the entire tutorial translation. I get to work and when I have it completed I will do the pull request for the complete translation. Best greetings

Stay safe

**Comment by jonniebigodes** [comment]
@josegarciamanez that's awesome to hear and we'll be looking forward to the translation. One thing that I wanted to mention to you, the tutorial will be getting some adjustments in the coming weeks. Nothing too much just a couple of adjustments to some of the snippets and some videos/images that need a bit of a refresher. I'll let you know once it's up.

Stay safe

**Comment by jonniebigodes** [comment]
@josegarciamanez just a heads up I'm putting in the "DO NOT MERGE" label while you work on this. To prevent accidental merges. Once you've updated the pull request I'll remove it.

**Comment by josegarciamanez** [comment]
@jonniebigodes, I understand that what should be done is to review the tutorial that is currently in Spanish or make a copy of the one in English and translate it completely?

**Comment by jonniebigodes** [comment]
@josegarciamanez based on the current state of the translation in comparison with the English version it requires a lot of work. Some if not most of the content is a bit outdated and also there's one section missing. So my best guess is to start from scratch. The upside to it is that you have some of the work already done with some of the Spanish translations. Wouldn't hurt for you to take a look at them.

**Comment by josegarciamanez** [comment]
Perfect, I get to work on the weekend and will try to get it ready as soon as possible to do the pull request.

**Comment by jonniebigodes** [comment]
@josegarciamanez that's great to hear. Just let me know and we'll get a proofreader to help us get it across :)

**Pull request closed without merging**
