### PR TITLE
Get vue styles working

### PR DESCRIPTION
**Pull request by samit4me**
Updated the "Reuse CSS" section of the vue docs to show how to reuse the CSS inside a vue app. It is also possible to import the CSS into `main.js` but if you did that it's likely you would also need to remove the default styles in `App.vue` as it would override what's in `index.css`. So I've updated to what I believe is the easiest solution.

### CODE REVIEW

**Comment by samit4me** [comment]
I just realised there is a "Keep your code in sync" section at the bottom pointing to https://github.com/chromaui/learnstorybook-code/commit/d1c4858 which probably needs updating also as it doesn't appear to be importing the styles either. I'm not 100% sure how to go about that at the moment. Does anyone have some ideas?

**Comment by tmeasday** [comment]
Thanks @samit4me! I'll update the source and merge this soon, probably as part of a general update to SB4 in the next day or two -- once it is released!)

(The source that needs to be changed is here: https://github.com/chromaui/learnstorybook-code btw, but it's slightly complicated changing it as you need to rewrite the git history)

**Comment by samit4me** [comment]
Sounds awesome @tmeasday, thank you for that 😃

**Comment by tmeasday** [comment]
Sorry this took so long @samit4me !

**Pull request merged**
