### PR TITLE
Chore: simplify wording in `vue/en/simple-component.md`

### PR DESCRIPTION
**Pull request by miclgael**
This is trivial, but I had to re-read this sentence a few times to understand. I think this PR will make it easier for the learner to parse.

### CODE REVIEW

**Comment by jonniebigodes** [comment]
@miclgael thanks once again for the amazing contribution we appreciate it. That turn of phrase was always a bit challenging in order to convey the right idea to our audience. With that in mind, would you be willing to make the same change to the other versions of the tutorial similar to what you did here?

Let me know once this is done and I'll gladly merge it.

**Comment by jonniebigodes** [comment]
Going to merge this. Thanks for the small but rather important contribution to the tutorial. Appreciate it 🙏 !

**Comment by miclgael** [comment]
Thanks @jonniebigodes - no worries - sorry I wasn't able to found the time!

**Comment by jonniebigodes** [comment]
No need to thank whatsoever. It's all good and I totally understand. We're all busy here 🙂!

Looking forward to your next contribution.

Hope you have a great weekend.

Stay safe

**Pull request merged**
