### PR TITLE
Update get-started.md

### PR DESCRIPTION
**Pull request by lewis738**
其他的则适用于 => 还有其他的教程适用于

### CODE REVIEW

**Comment by jonniebigodes** [comment]
@lewis738 thanks for taking the time and effort into creating this pull request and helping us with the translation. We appreciate it! I'd like to ask you something If you're ok with it. Instead of making small pull requests with each page, which will be a bit more tricky to triage, what do you think about consolidating it into a single pull request that will be much easier for us to triage and proofread? Sounds good to you? Let me know and we'll go from there. 


Hope you have a great weekend!

Stay safe

**Comment by lewis738** [comment]
Hi, it's a great idea to consolidate small pull requests into a single one and I would love to do that. But the work might take a little more time, so I might push the request for all the pages after a period. Thanks for your time and patience.

Hope you have a great weekend! Stay safe!

**Comment by jonniebigodes** [comment]
@lewis738 that's great that you're willing to work on the updates for the translation, we're thankful for it 🙏 ! And don't worry about it, take your time. 

Also, no need to apologize whatsoever,, glad that you're on board with the idea. Hope you don't mind, I'm going to close this and the other pull request so that they don't get accidentally merged. Sounds good?


Ping me when you have the updated translation pr up and we'll go from there.

**Comment by lewis738** [comment]
Hi,&nbsp;it's&nbsp;a&nbsp;great&nbsp;idea&nbsp;to&nbsp;consolidate&nbsp;small&nbsp;pull&nbsp;requests&nbsp;into&nbsp;a&nbsp;single&nbsp;one&nbsp;and&nbsp;I&nbsp;would&nbsp;love&nbsp;to&nbsp;do&nbsp;that.&nbsp;But&nbsp;the&nbsp;work&nbsp;might&nbsp;take&nbsp;a&nbsp;little&nbsp;more&nbsp;time,&nbsp;so&nbsp;I&nbsp;might&nbsp;push&nbsp;the&nbsp;request&nbsp;for&nbsp;all&nbsp;the&nbsp;pages&nbsp;after&nbsp;a&nbsp;period.

Thanks&nbsp;for&nbsp;your&nbsp;time&nbsp;and&nbsp;patience.

Hope&nbsp;you&nbsp;have&nbsp;a&nbsp;great&nbsp;weekend!&nbsp;Stay&nbsp;safe!

Fr:&nbsp;Lewis




---Original---
From: ***@***.***&gt;
Date: Sat, May 7, 2022 00:58 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [chromaui/learnstorybook.com] Update get-started.md (PR #598)




 
@lewis738 thanks for taking the time and effort into creating this pull request and helping us with the translation. We appreciate it! I'd like to ask you something If you're ok with it. Instead of making small pull requests with each page, which will be a bit more tricky to triage, what do you think about consolidating it into a single pull request that will be much easier for us to triage and proofread? Sounds good to you? Let me know and we'll go from there.
 
Hope you have a great weekend!
 
Stay safe
 
&mdash;

**Pull request closed without merging**
