### PR TITLE
Translation of Intro to Storybook for React into Spanish

### PR DESCRIPTION
**Pull request by luisabellan**
### Description

I'm translating the following files into Spanish:

- [x]   ./content/intro-to-story-book/react/es/creating-addons.md

- [x]   ./content/intro-to-story-book/react/es/using-addons

### CODE REVIEW

**Comment by luisabellan** [comment]
@jonniebigodes Hi, I just wanted to notify you that I've just created the (draft) PR and I'm working on it. Any feedback will be appreciated.

**Comment by luisabellan** [comment]
Hello @jonniebigodes,  I've just finished the translation.

**Comment by jonniebigodes** [comment]
@luisabellan to make our lives easier in getting this merged, could i ask a favor of you? Package the tutorial translation in one single pull request if you don't mind? Also on a side note i'm going to leave you with a tip for a good extension that you can use with vscode when translating. Add [this](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) (it has spanish support) one and you won't need to add/commit the `.markdownlint.json`. That's the one i've been using when translating content and so far no issues. 

Let me know once you have the pull request up so that i can start proofreading it.

Stay safe

**Comment by luisabellan** [comment]
Hello @jonniebigodes, I have already merged everything related to the translation into this PR. I have closed the other PR related to typos. 
There is another PR but that one is not related to de Spanish translation, but the English one.

**Comment by luisabellan** [comment]
That vscode extension is great. Thanks for sharing! 👍

**Comment by jonniebigodes** [comment]
@luisabellan probably a bit of miscommunication here. I was checking the pull request and your forked repository and there's still items that need to be addressed. In this pull request that you created you only addressed the translation partially. For accuracy what we aim for is a full translation from the Get Started page up to the Bonus: Create addons page. With the content and the snippets updated to match the english version. 

Based on what i see, content  is still based on outdated content, same as the snippets (they are focused on version 5.2 of Storybook). And if we're aiming for accuracy it should reflect the latest version of Storybook (6.1.x). 

The upside to this is the following, the bulk of the work is already done, there's a couple of bits and pieces that need to be included in the documentation. 

My recommendation would be to check the english version and factor in the changes to your translation. If you need help i'm in [Storybook's Discord Server](https://discord.gg/UUt2PJb) (same username as here), message me and we'll figure it out and get the translation merged. Sounds good?

Stay safe

**Pull request closed without merging**
