### PR TITLE
chore rewording to angular documentation and svelte

### PR DESCRIPTION
**Pull request by jonniebigodes**
With this pr some changes were introduced to the documentation.

Going by framework:
- angular
   - creating addons
     reworded to match already existing documentation
  - data 
     Minor rewording to make it more clearer
  - deploy
     Minor rewording to match the other versions of the documentation
  - get started
    Minor rewording to match existing documentation, more specifically the mentions to the files that need to be created/updated.
  Updated the svn command to it's correct place, more specifically the assets folder is inside `src`

  - Screen 
     Some minor rewording applied.
   - Simple component
     Minor tweaks to the code snippets to incorporate the files that need to be created/updated like the remainder documentation.

   - Test
     Minor rewording to match the other versions of the tutorial.

   - Using addons
     Some rewording was applied to match the other versions of the documentation.

  The portuguese translation got it's long overdue translation update to match the changes in the original version.

- svelte
  - Using addons
    Some minor rewording to match the existing documentation, the code snippet where's knobs is introduced was cut down to keep the focus on what's intended.
  - Create addons
    The section was updated to match the existing version of the documentation.

Feel free to provide feedback

### CODE REVIEW

**Comment by jonniebigodes** [comment]
With the latest commit the svelte using addons was updated to prevent introducing a error in the code snippet. When the file was commited before it introduced the following with husky and the linters:

```html
<input
  type="text"
  readonly
  value="{task.title}"
  placeholder="Input title"
  style="text-overflow: ellipsis;"
/>
```` 
and it should be:
```html
<input
  type="text"
  readonly
  value={task.title}
  placeholder="Input title"
  style="text-overflow: ellipsis;"
/>
```
If the reader checks this and tests in Storybook, he'll get displayed the text "task.title" instead of the actual context of the title.

**Comment by jonniebigodes** [comment]
@tmeasday if you don't mind when you're able can you trigger a new build in netlify as it seems there was a issue with netlify earlier and i would like to check the preview to see if everything is alright and then i'll merge this if you're ok.

**Comment by jonniebigodes** [comment]
@domyen can you retrigger a preview deploy on netlify so that i can check if everything is alright with the latest commit. With that would prevent me to make a unecessary commit and push to the repo. Thanks in advance

**Comment by domyen** [comment]
@tmeasday has access to the Netlify account (and forgot to add me 😂). Go ahead and push a new commit for now, no worries.

**Comment by jonniebigodes** [comment]
@domyen with the latest commit i removed the reference from the react version. I know that's beyond the scope of the pr. But it aims for two things. One retrigger the build process and two remove one lingering mention of `git init` when actually CRA has already setup the local repo. So no need to initialize it 2 times.

**Comment by jonniebigodes** [comment]
@ghengeveld i saw that you commited to master yesterday and it seems that introduced alot of issues with the prs that are open as of now. Also it's breaking the build in CircleCI and netlify previews as the node version is not supported with one or more dependencies that are used. 

Care to give some insights on this matter. Also @tmeasday and @domyen some feedback on your end would be appreciated.

**Comment by ghengeveld** [comment]
@jonniebigodes Oops, looks like I managed to update some dependencies along with the content changes. I'll revert the dependency changes.

**Comment by ghengeveld** [comment]
I reverted the non-content changes and I've resolved the conflict on your PR. I'll take a look at other PRs with conflicts too.

**Comment by jonniebigodes** [comment]
Going to merge this and make a follow up pr to fix the documentation in the testing section per latest pr that addressed the package naming.

**Pull request merged**
