### PR TITLE
Upgrade design system to the latest version

### PR DESCRIPTION
**Pull request by Andarist**
To make the Emotion migration easier - let's first upgrade the design system to the latest version.

### CODE REVIEW

**Comment by jonniebigodes** [comment]
Hi @Andarist and sorry for the delayed response, but I was otherwise engaged in other aspects of the documentation! Hope you don't mind but I'll take a look at this more closely tomorrow (Friday) and hopefully, if nothing is breaking, I'll gladly merge it! I'm more than thankful for the time you've put into this pull request, really appreciate it.

I'll follow up with you once I've checked it!

Sounds good?

**Comment by Andarist** [comment]
Sure thing, since this doesn't bring any changes to the stories - it's not a blocker to me

**Review by jonniebigodes — APPROVED** [review]
Looks good on my end! I'm going to reach out to Kyle Gach and if he's also ok with it. I'll gladly merge this. 

Appreciate the help on this. Have a great weekend.

Stay safe

**Comment by winkerVSbecks** [comment]
This looks good to me, merging now so that we can move on to the emotion migration.

**Pull request merged**
