### PR TITLE
[Fix] Add installation step to avoid breaking

### PR DESCRIPTION
**Pull request by halian-vilela**
Adding steps in the tutorial to fix:
* https://github.com/chromaui/learnstorybook.com/issues/107
* https://github.com/storybookjs/storybook/issues/7232
* https://github.com/storybookjs/storybook/issues/7231

### CODE REVIEW

**Comment by domyen** [comment]
@halian-vilela thanks so much! 🙏

Any chance this applies to the Vue and Angular versions as well?

**Comment by halian-vilela** [comment]
> @halian-vilela thanks so much! 🙏
> 
> Any chance this applies to the Vue and Angular versions as well?

Hey @domyen, you're welcome! 

In fact, this came from a very thorough help of a nice guy (jitpomi) in the discord server!
 
I'm not sure if it applies to the other versions, but since it's seems more like a babel/build issue, I guess it should work...

**Comment by nclairesays** [comment]
I'm glad I stumbled upon this solution because I also got that error while doing the tutorial! Hope they merge this in soon!

**Comment by nclairesays** [comment]
Thank you! I'm glad I stumbled upon this solution because I also got that error while doing the tutorial! Hope they merge this in soon!

**Comment by tmeasday** [comment]
This is odd, I thought `babel-plugin-macros` was automatically added by CRA. If that's not the case we could maybe revisit this approach.

**Comment by shilman** [comment]
Hey @mrmckeb this is related to your CRA preset refactor. Mind taking a quick look?

**Comment by mrmckeb** [comment]
Hi all, yes @shilman is correct, macros will be supported properly in the new preset we're working on - it should be in beta very soon.

The old config was trying to replicate what CRA had, and only brought across some of the config. I've designed the new preset to use as much as possible from CRA.

Related PRs are here:
https://github.com/storybookjs/presets/pull/25
https://github.com/storybookjs/storybook/pull/7696

**Comment by tmeasday** [comment]
OK, let's merge this PR then in the short term and hopefully we can revert it after the PRs above are release.

**Comment by tmeasday** [comment]
Thanks for helping out here @halian-vilela

**Comment by tmeasday** [comment]
@domyen this was a technique designed for CRA so I don't think it's relevant to Angular/Vue

**Comment by halian-vilela** [comment]
Hey @tmeasday, thanks for the merge. You're welcome!

I'm wondering if it would still be relevant for older versions of CRA even if it gets updated, maybe we should keep a warning to still try this config if the version of CRA does not have the corrections.

**Comment by mrmckeb** [comment]
This preset should support al versions of CRA, but we've only been testing on 3.x+ for now.

I'd always always recommend keeping `react-scripts` up-to-date ;)

**Comment by tmeasday** [comment]
> I'm wondering if it would still be relevant for older versions of CRA even if it gets updated, maybe we should keep a warning to still try this config if the version of CRA does not have the corrections

This particular document is part of a tutorial that people will be following, so they will have just installed CRA; I think it's fair to assume they are on the latest version of everything.

In the docs we can add the caveats about what can go wrong, but a tutorial doesn't try to cover that ground. Of course it needs to work in the first place!

**Pull request merged**
