### PR TITLE
Remove components directory reference

### PR DESCRIPTION
**Pull request by MichaelArestad**
I believe this is the first and only time the `components` directory is referenced. I know it's pretty common to have on projects, but for the purposes of this tutorial, it would be good to remain consistent.

### CODE REVIEW

**Comment by jonniebigodes** [comment]
@MichaelArestad if you don't mind, I'm going to merge this after 6.3 lands if you don't mind. I'll have to rebase the code base and factor in these changes? Sounds good?

**Comment by MichaelArestad** [comment]
Sounds good to me!

**Comment by jonniebigodes** [comment]
@MichaelArestad going to close this in favor of #520. It seems that the document chapter of the tutorial had a small issue that required some additional work. I factored in the changes you've introduced here in the other pr

**Comment by MichaelArestad** [comment]
Awesome. Thanks!

**Comment by jonniebigodes** [comment]
no problem

**Pull request closed without merging**
