### PR TITLE
Intro to Storybook Spanish translation (React) 

### PR DESCRIPTION
**Pull request by lmac-1**
Hello again!

I previously translated this tutorial in #693. This PR updates the Spanish translation for the Intro to Storybook tutorial to match the current English version. 

If you have any questions or feedback, let me know.

Thanks again and have a great day!

### CODE REVIEW

**Comment by lmac-1** [comment]
@jonniebigodes you're welcome. Sounds good to me, whenever you have time :)

Hope you're having a great September!

**Comment by jonniebigodes** [comment]
@lmac-1, sorry for the radio silence, but I plan to look into the translation sometime this week so we can get it in. Before doing that, I was wondering if you could adjust it to match the changes in #784 so that we can align this to match the current version.

Looking forward to hearing from you.

Hope you have a great week.

Stay safe

**Comment by jonniebigodes** [comment]
@lmac-1 I've checked, and aside from the changes mentioned in #784 that need to be added here, the translation is looking fantastic. I've checked, and all is good so far. I cannot thank you enough for this 🙏 ! Let me know once you've addressed the changes, and I'll take a look. If nothing stands out, I'll get the updated translation published.

Have a great day.

**Comment by lmac-1** [comment]
Hi @jonniebigodes, weirdly enough I was just thinking about this PR today - we must be connected! 

I will get on the remaining changes now and update when finished 😌

Thanks!

**Comment by lmac-1** [comment]
Okay I think I've done the minor updates, nice and easy :-) 

Should be good to merge once you've given it a quick check but let me know if you need something else. 

I'm also working on the Design System translation in a branch and will report back when finished.

Thanks again!

**Pull request merged**
