### PR TITLE
Update intro-to-storybook/ja

### PR DESCRIPTION
**Pull request by UHAsikakutou**

### CODE REVIEW

**Review by jonniebigodes — CHANGES_REQUESTED** [review]
@UHAsikakutou appreciate the time you took to put together this pull request and add the much-deserved updates to the translation. 🙏 ! I've checked and left a couple of suggestions for you to look into when you have a moment. Also, if you're okay with it, as you are already working on updating the translation, can you check #768 and include those changes here? For context they're small adjustments to some of the examples.

Let me know once you've addressed it, and I'll be more than glad to take another pass at it so that we can get someone in the community to review it. 

Will that work for you? 

Have a fantastic day.

Stay safe

**Comment by UHAsikakutou** [comment]
Thank you for reviewing my code, @jonniebigodes .
I have made the following fixes:

    - Removed Japanese comments in the example code
    - Updated the version of `chromatic.yml` in `deploy.md`
    - Corrected some of my translation errors

**Comment by UHAsikakutou** [comment]
Sorry, I missed one of your reviews.
I have changed the version of `actions/checkout` to 4.

**Review by jonniebigodes — APPROVED** [review]

**Comment by jonniebigodes** [comment]
@UHAsikakutou, I'm sorry for the "radio silence". It's been a busy time here at Storybook. I've checked, and all is good on my end. I'm more than glad to merge this and release the updated version of the translation. 

Hope you have a fantastic week

Stay safe

**Pull request merged**
