### PR TITLE
Syntax error

### PR DESCRIPTION
**Pull request by luisabellan**
crossorigin -->  crossOrigin={"true"}

### CODE REVIEW

**Comment by jonniebigodes** [comment]
@luisabellan thank you for the time and effort you put into this. I'll defer to @winkerVSbecks on this one. One key item that i'm concerned about is why did you delete the `yarn.lock` file?

@winkerVSbecks can you chime in on this one? It seems that this pull request is currently following up on #400 that was recently merged.

**Comment by winkerVSbecks** [comment]
@jonniebigodes the crossOrigin bit is good. Good catch @luisabellan.

However, yes the `yarn.lock` should not have been modified in this PR.

**Comment by luisabellan** [comment]
@jonniebigodes thank you and sorry about yarn.lock, I have just unstaged it from the commit. I hope it helps.

**Comment by jonniebigodes** [comment]
Closing this as the fix is already in play @luisabellan . Looking forward for the Spanish translation that you're working on. Just a heads up, i've merged a pull request with some changes that you might want to factor in. 

Stay safe

**Pull request closed without merging**
