### PR TITLE
Update Intro to Storybook (React/Japanese)

### PR DESCRIPTION
**Pull request by chameleonhead**
Update to latest version of English document. Including following PR.

- #374 
- #427

@match5121 could you proofread this PR's changes?

### CODE REVIEW

**Comment by jonniebigodes** [comment]
@chameleonhead wow! Thank you for taking care of this already. Really thankful, let me know when it's good to go and i'll gladly merge it :)

Stay safe

**Review by match5121 — COMMENTED** [review]
@chameleonhead The proofreading is complete. I can have found no correcting point.

**Comment by chameleonhead** [comment]
@match5121 Thank you for proofreading.

@jonniebigodes It's OK to merge. Please merge this PR. Thank you.

**Comment by jonniebigodes** [comment]
@chameleonhead will do. Merging this. But just a heads up for you. Don't know if you've taken notice, but i've created #431 and the tutorial is going to be updated shortly regarding this. I'll let you know once the changes are in place and you can adjust accordingly. Once again, thank you very much for the update on the tutorial and @match5121 for the time you've taken to proofread it.

Stay safe both of you

**Pull request merged**
