### PR TITLE
fix header variation on 404 page

### LINKED ISSUE #454: Header is missing from Not found page
On [this 404 page](https://storybook.js.org/tutorials/design-systems-for-developers/sfeaf) the header is missing for some reason. Ideally, we'd have the same 404 page as the /frontpage. [Example here »](https://storybook.js.org/djkfa;je)

Since the tech stacks between the sites are so similar, you could probably copy paste [this component](https://www.chromatic.com/component?appId=5be26744d2f6250024a9117d&name=Frontpage%7Cscreens%2FNotFoundScreen%2FNotFoundScreen&buildNumber=717) into the page with some minor tweaks.

image

### PR DESCRIPTION
**Pull request by winkerVSbecks**
fixes #454

### CODE REVIEW

**Comment by domyen** [comment]
Nice, I see the updated message but the header is still white on white:

image

**Comment by winkerVSbecks** [comment]
Strange. It renders correctly on `/tutorials/404` but not for other breaking routes.

**Comment by winkerVSbecks** [comment]
@domyen updated with the fix

**Comment by domyen** [comment]
Nice! Merging!

**Pull request merged**
