### PR TITLE
Removes reference to SVN because it is no longer 1999

### PR DESCRIPTION
**Pull request by obeid**
Because this shit fucked with me real hard, and on the first page of your otherwise very nice book.
Like why? 

https://www.youtube.com/watch?v=shbxUe-S2V8

### CODE REVIEW

**Comment by obeid** [comment]
1999 was a Prince reference, but then I realized Subversion was actually made in 1999. 👍

**Comment by domyen** [comment]
Wow, I did not know about `degit`. We have an [open PR](https://github.com/chromaui/learnstorybook.com/pull/340) to swap out svn with curl. This seems even easier. What do you think @jonniebigodes?

**Comment by jonniebigodes** [comment]
@obeid thank you for the time and effort you put into this. I'm going to take a look at it and see if works with all the frameworks being used with the tutorial. Should that be the case we could use the `degit` package instead and we adjust the wording (the aside that was removed) so that the reader can get a sense of what he/she is doing. 

Also, on a maintainer's perspective if you don't mind please update the pull request description and title, also avoid using profanities. It doesn't sit well with us. I personally liked the Prince reference (brings me back to my late teens :P), but other people and maintainers might not see it that way.

Sounds good?

**Comment by jonniebigodes** [comment]
@obeid thank you for the time and effort you put into this. I'm going to take a look at it and see if works with all the frameworks being used with the tutorial. Should that be the case we could use the `degit` package instead and we adjust the wording (the aside that was removed) so that the reader can get a sense of what he/she is doing. 

Also, on a maintainer's perspective if you don't mind please update the pull request description and title, also avoid using profanities. It doesn't sit well with us. I personally liked the Prince reference (brings me back to my late teens :P), but other people and maintainers might not see it that way.

Sounds good?

**Comment by obeid** [comment]
@jonniebigodes To _fuck with_ something is not the same as to _fuck_ said thing. 

The aside seemed to exist mainly to justify the use of Subversion, the user already got a sense of what they are doing from the previous sentence. 

I have turned off allowing edits by maintainers. Take my free labor as it is, or leave it.

**Comment by obeid** [comment]
FWIW `curl` doesn't come pre-installed on Ubuntu, arguably the most popular Linux distribution out there.

**Comment by jonniebigodes** [comment]
@obeid regarding your last comment. Hence why it hasn't been merged. I had on my todos to come up with a better way.

On the topic at hand.

What you're introducing won't work as is. I just tested it on a fresh project.

If you issue this:

```bash
npx degit https://github.com/chromaui/learnstorybook-code/branches/master/public/icon public/icon
```
It clones only the folder as you can see below, this is the result of your proposed change.

degit-finder

Vscode opened will reflect the behavior and show me the following

degit-vscode


Checking the documentation for [degit](https://github.com/Rich-Harris/degit#specify-a-subdirectory) what needs to be used is:

```bash
npx degit chromaui/learnstorybook-code/public/font public/font 
```

This will yeld the following result:

degit-working-vscode
finder-degit-working

If you're willing to make the changes and once i vet if it works for the other frameworks this will be merged.

Regarding your other comment. I stand for what i've said, i understand what you're meaning, but others don't hence why i mentioned it.

Stay safe

**Comment by jonniebigodes** [comment]
@obeid Going to close this in favor of #370. The documentation is now updated globally to use degit. 

Nonetheless thank you for the time and effort you put into this pull request and offer a better way to pull in the files/folders and improve the documentation.

We really appreciate it.

Stay safe.

**Pull request closed without merging**
