### PR TITLE
(design-systems ko version) change master to main

### PR DESCRIPTION
**Pull request by sosunnyproject**
regarding #402 i changed words that described`master` branch to `main` branch in code snippets & korean explanations in ko translation documents. (I didn't change en documents)
If there's anything else I need to edit on my end, please let me know. 
Stay safe!

### CODE REVIEW

**Comment by jonniebigodes** [comment]
@sosunnyproject one item and we're good to go. With the introduction of the Korean translation of the tutorial Intro to Storybook in order to properly display the language (in this case Korean) the content was placed under a folder called `kr` as you can see [here](https://github.com/chromaui/learnstorybook.com/tree/master/content/intro-to-storybook/react). With i had to do a follow pull request to address your translation. If you're able and adjust accordingly we'll get this merged and the awesome work you and your fellow collaborators will be complete.

Let me know once you made the changes and we'll get this merged.

Once more thank you for the speedy follow up pull request. We really appreciate it :)

Stay safe

**Comment by sosunnyproject** [comment]
@jonniebigodes hello! thanks for follow up!
I just realized ko was changed into kr when merged with main branch. Actually, [according to ISO](http://www.mathguide.de/info/tools/languagecode.html), **ko** is an official code for **korean language**. (kr is for Korea, country name. ) We know that previous contributor on intro to storybook named her folder 'kr' but we decided to use 'ko' because that is more accurate. 
We would appreciate if you can discuss about this with your team. Thank you and stay safe!

**Comment by jonniebigodes** [comment]
@sosunnyproject the issue is addressed regarding iso code. All Korean content now lives in the "ko" folder. Sorry for that bit of "fumble fingering" on my end. If you can, could you check and fix the conflicts and i'll gladly merge this. 

Let me know

Stay safe

**Comment by jonniebigodes** [comment]
Closing this

**Comment by jonniebigodes** [comment]
Closing this

**Pull request closed without merging**
