### PR TITLE
Chore: Adds the Visual testing initial content

### PR DESCRIPTION
**Pull request by jonniebigodes**
With this pull request, the Visual Testing handbook's content is introduced.

What was done:
- Updated the content of the chapters.
- Introduced the automate and conclusion section
- Added initial assets

Feel free to provide feedback

### CODE REVIEW

**Comment by jonniebigodes** [comment]
With the latest commit, I made some adjustments to the automate tutorial section and also included some of the missing assets. Also some minor tweaks to the wording here and there

**Review by winkerVSbecks — APPROVED** [review]
❤️ it

**Comment by jonniebigodes** [comment]
Caught a couple of issues with the tutorial. Applied some fixes with the latest commit. Let me know if you're ok with it @domyen and @winkerVSbecks

**Comment by domyen** [comment]
Thank you! We're close 🤞

**Pull request merged**
