### PR TITLE
More detail on installing Degit

### PR DESCRIPTION
**Pull request by sosensible**
I was not sure if this was something that was installed or not on its own. Then today, after speaking on this, the same question is coming from others.

### CODE REVIEW

**Comment by jonniebigodes** [comment]
@sosensible, thanks for taking the time and effort to create this pull request and helping us improve our tutorials. To give you a bit of context, running `npx somepackage` does not install the package but instead downloads it, caches it, and executes it. You can read more about it [here](https://nodejs.dev/en/learn/the-npx-nodejs-package-runner/). We went with this approach to avoid having our readers install another package just to get started with the tutorial, or having them go through the process of forking the template repo, cloning it, and running it on their machines and inadvertently having them push a pr against the template repo owned by Chromatic which could cause some confusion. 

One thing that we could do is clarify what the command actually does, and should the reader wants to install it is up to them.

What do you think? Sounds good to you?

Hope you have a great week.

Stay safe

**Comment by sosensible** [comment]
I think we need fresh eyes to answer the question, first pass users. I
don't have fresh ones ATM... but will stay alert as more jump in.

Also, I will be submitting some fixes to the VUEX implementation. I had to
debug and fix that when I went through the turorial.

*John Farrar*
*SOSApps*
*Servant Oriented Software*

**Comment by jonniebigodes** [comment]
Totally agree with you on the fresh eyes. And please do. Looking forward to seeing the changes to the data/screen sections where VueX comes into play. Before committing to them, are you ok with opening up an issue detailing it a bit more so that we can continue the discussion there and polish the changes so that once it's committed, it's a simple click of a button to merge them in

Looking forward to reading it.

**Comment by jonniebigodes** [comment]
@sosensible, if you're ok with opening up an issue with the feedback collected here also, I wanted to let you know that we've moved away from VueX as the data provider library for Pinia as per Vue recommendations. The tutorial was updated accordingly, and please let me know if you spot any issues.

Looking forward to hearing from you.

Hope you have a great weekend.

Stay safe

**Comment by jonniebigodes** [comment]
Closing this pr for now. Let me know if you still wish to work on this, and I'll gladly follow up with you on our issue tracker until we find a suitable solution that helps you go through the tutorial without any issues.


Hope you have a fantastic weekend.

Stay safe

**Pull request closed without merging**
