### PR TITLE
Changed deprecated loader example in Build

### PR DESCRIPTION
**Pull request by chiangs**
Console output: `DeprecationWarning: @storybook/addon-storysource/loader is deprecated, please use @storybook/source-loader instead`

### CODE REVIEW

**Comment by flexbox** [comment]
I have the same issue here :)

@chiangs Do you think you are going to have some time to update your PR ?

**Comment by chiangs** [comment]
@flexbox I don't have the permissions to fix the conflict. someone with write access has to approve this.

I've already updated my fork and I don't have any conflicts on my side.

**Comment by jonniebigodes** [comment]
going to ping @domyen or @tmeasday to address this issue so that the documentation can move forward. Sounds good @chiangs and @flexbox ?

**Comment by domyen** [comment]
Thank you @chiangs 💪

**Pull request merged**
