### PR TITLE
Comment file names in code snippets

### PR DESCRIPTION
**Pull request by calaway**
Thank you for the wonderful tutorial!

While coding along, it wasn't always immediately clear to me exactly what file was referred to in each snippet. I have generally been able to determine from the context, but the tutorial would be that much simpler for me if it were obvious and that additional cognitive load wasn't required.

Please let me know if you think this is useful and would be merged in. If so then I'll finish it on the remainder of the tutorial. 

Thank you again for your excellent work on this project!

### CODE REVIEW

**Comment by jonniebigodes** [comment]
@calaway  I read the changes and i don't see why it shouldn't be ok to merge. I understood where you're going, even if the tutorial is already simplified and available to everyone this small addition makes it even more accessible.  I'll defer to @tmeasday  or @domyen for the approval

**Comment by tmeasday** [comment]
This seems a good approach in lieu of something more complicated. Thoughts @domyen?

**Comment by calaway** [comment]
I finished adding comments denoting the file name to the remaining snippets within the English React tutorial. If you approve of the changes, go ahead and merge it in.

Just FYI, this isn't a pattern I made up. I have seen it on many other tutorials ([here is an example](https://auth0.com/blog/building-a-component-library-with-react-and-storybook/#Creating-Multiple-Stories-for-a-Component-in-Storybook)) and found it helpful enough to want to add it here.

Thank you all for your contributions to open source. This tutorial really helped me out a lot.

**Comment by domyen** [comment]
Thank you @calaway 🙏

**Pull request merged**
