### PR TITLE
add redux: Provider & store to storybook

### PR DESCRIPTION
**Pull request by andihaki**
fixing issue:

Could not find "store" in the context of "Connect(PureTaskList)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(PureTaskList) in connect options.

### CODE REVIEW

**Comment by tmeasday** [comment]
Hi @andihaki - I think perhaps you missed the bit where we export the original (non-redux) `TaskList` as `PureTaskList` and then the connected one as the default export?

**Comment by andihaki** [comment]
Hi @tmeasday - already did what u said in my code. but still get error until i add this 3 line of codes: 
```javascript
import { Provider } from "react-redux";
import store from "../lib/redux";
.addDecorator(story => <Provider store={store}><div style={{ padding: '3rem' }}>{story()}</div></Provider>)
```
if you think everything is fine, then just closed my PR 👍

**Comment by tmeasday** [comment]
@andihaki is it possible you wrote:

```js
import PureTaskList from './TaskList';
```

rather than
```js
import { PureTaskList } from './TaskList';
```

**Comment by andihaki** [comment]
wow, you're right. it was my bad

**Pull request closed without merging**
