### PR TITLE
Update creating-addons.md

### PR DESCRIPTION
**Pull request by BanlyTong**

### CODE REVIEW

**Comment by jonniebigodes** [comment]
@BanlyTong just one thing that i would like for you to do if you don't mind.

The code snippet used after the phrase :

> The way we'll be attaching the list of assets to the stories is through parameters, which is a Storybook option that allow us to inject custom parameters to our stories. The way to use it, it's quite similar on how we used a decorator in previous chapters.

More specifically 
```javascript
storiesOf("your-component", module)
  .addParameters({
    assets: ["path/to/your/asset.png"]
  })
  .addDecorator(/*...*/)
  .add(/*...*/);
```
If you could change it to 
```javascript
export default {
  title: 'Your component',
  decorators: [
    /*...*/
  ],
  parameters: {
    assets: ['path/to/your/asset.png'],
  },
  //
};
```
It would be excelent as it would make the entire section aligned to the CSF format. 

And thank you for this small but rather important contribution.

**Comment by BanlyTong** [comment]
@jonniebigodes I changed it.
Thank you and the community I had a good time learning storybook, so I'm glad to have such a small contribution.
Also, give a better experience for the next learners.

**Comment by jonniebigodes** [comment]
@BanlyTong i just saw it and it looks really nice. Once again thank you for this. 

Also i see that you're hailing from Cambodia. If you're up for it and willing i believe that the team would benefit a translation to allow the tutorials reach a broader audience, what do you think @domyen  and @tmeasday ?

**Comment by domyen** [comment]
+1 @jonniebigodes that sounds excellent.

**Comment by jonniebigodes** [comment]
@domyen i think this is good to go. Merge when ready if you can

**Pull request merged**
