### PR TITLE
feature(angular/en) add addons chapter

### PR DESCRIPTION
**Pull request by geromegrignon**

### CODE REVIEW

**Comment by tmeasday** [comment]
Thanks @geromegrignon. Am I right in saying this still looks like the React code?

**Comment by geromegrignon** [comment]
Right, i was so focused on checking external links that i forgot to convert to Angular!

**Comment by norato** [comment]
I can add translations to portuguese here

**Comment by domyen** [comment]
@norato that'd be awesome! Make a PR?

@geromegrignon any chance you have time to update the code to angular?

**Comment by domyen** [comment]
This doesn't seem active anymore 😅 Closing this because we're refreshing the site. Reopen if more commits are planned.

**Pull request closed without merging**
