### PR TITLE
Korean Translation: DesignSystemsForDevelopers all chapters

### PR DESCRIPTION
**Pull request by sosunnyproject**
- Translated English into Korean for all chapters in Design Systems content.
- Each person translated 2-3 chapters
- Did peer review within our team: each chapter had at least 1 reviewer other than a translator

Hello! As I've mentioned korean translation work on this thread (https://github.com/chromaui/learnstorybook.com/issues/3) , me and 3 other people contributed on translating Design Systems chapters (https://www.learnstorybook.com/design-systems-for-developers/) into Korean. We already did peer reviews for one another but would still appreciate any feedback or suggestion. 

Thanks!

### CODE REVIEW

**Comment by jonniebigodes** [comment]
@sosunnyproject sorry for the radio silence. I've been hard at work tackling other aspects of the documentation and did not have the time to further vet it. First and foremost thank to both you and your team for the time you put into the translation we really appreciate it. As a policy i asked around the community for a proofreader and so far no one has come forward to help us with this. On my end, code wise i'm going to take a look at it and see if anything needs updating. If not i'm merging it. 

Sounds good?

Stay safe.

**Comment by jonniebigodes** [comment]
@sosunnyproject from my end, content wise, we're almost good go go. A couple of items need attention, those related to the architecture and distribute section. If you could adjust your pull request according to #402 as per the new policy in GitHub branch naming. Let me know once you've made the changes and we'll be good to go and merge this. Really thrilled to see this tutorial as the Intro to Storybook one translated into Korean. 

My many thanks to you and your team for the time and effort you put into this.

Stay safe

**Comment by jonniebigodes** [comment]
@sosunnyproject i'm going to merge as is and once you have the chance, create a follow up pull request that addresses #402 . Sounds good?

Once again thank you and your team for the effort you put into this.

Stay safe all of you

**Comment by sosunnyproject** [comment]
@jonniebigodes 
thank you!! i will let my collaborators that our translation has been merged. 
sorry for late check. i will create a follow up pr now :) 
stay safe!

**Comment by jonniebigodes** [comment]
@sosunnyproject no need to thank me. Me personally and the rest of the team is really thankful for the time and effort you and your collaborators put into this. 

Stay safe

**Pull request merged**
