### PR TITLE
Upgrade to Emotion 11

### PR DESCRIPTION
**Pull request by Andarist**

### CODE REVIEW

**Review by ndelangen — APPROVED** [review]

**Review by winkerVSbecks — APPROVED** [review]

**Comment by winkerVSbecks** [comment]
@Andarist LGTM but Chromatic didn't run on this PR for some reason

**Comment by Andarist** [comment]
@winkerVSbecks it might be because I don't have write permissions to this repo - the action is configured to run on `push` and that doesn't run on forks. Arguably my previous PRs (such as [this](https://github.com/chromaui/learnstorybook.com/pull/544)) were also from a fork and they managed to run this action successfully - but last time I had write permissions (IIRC). So that's a very probable reason behind this.

**Comment by winkerVSbecks** [comment]
@Andarist good point. @ndelangen any suggestions of how to run Chromatic on this PR to update the baselines or should we just merge it and update baselines after the merge?

**Comment by Andarist** [comment]
@winkerVSbecks we could replace `push` with `pull_request` on the list of triggers and authorize the run if needed. Using both `push` and `pull_request` at the same time is not the best here as **both** would get triggered for PRs created by members of your team (which is somewhat odd and I would love to learn how one can avoid this but I couldn't figure it out so far).

**Comment by Andarist** [comment]
I have just gone with this change and the Chromatic action has been started. Let's see what happens.

**Comment by winkerVSbecks** [comment]
@Andarist it failed cause secrets aren't passed to the action executed from a forked repo.

**Comment by Andarist** [comment]
Ah yes, this is annoying - perhaps if you rerun it then it would be shared with this run? If it doesn't work then you might want to create a dummy PR using my latest commit

**Comment by winkerVSbecks** [comment]
Same issue, I'm running tests here: https://github.com/chromaui/learnstorybook.com/pull/601

**Comment by winkerVSbecks** [comment]
All tests passed without any changes. Good to merge.

**Comment by chantastic** [comment]
So sorry that I missed this yesterday.
Retroactively, it looks good 🥲

Thanks @Andarist!

Also, were you at Reactathon this week? I thought that I might have seen you in passing but wasn't sure.

**Comment by Andarist** [comment]
Ye, we've crossed paths somewhere there 😉

**Comment by chantastic** [comment]
oh bummer! next time we'll have a proper convo

**Pull request merged**
