### PR TITLE
Follow up on #277

### PR DESCRIPTION
**Pull request by jonniebigodes**
This small pr is a follow up on #277. 
Based on the comment [here](https://github.com/chromaui/learnstorybook.com/pull/277#issuecomment-604536270) now the order of the icons/frameworks are corrected. 

As previously this was the resulting in a contradiction with the comment above as you can see below:

storybook_framework_misaligned

On the left storybook running locally and on the right the development preview for ember. And the ember icon is the first one and it shouldn't.

@domyen @kylesuss when you're able, care to take a look? Also let me know if that's the intended order of the frameworks.

Feel free to provide feedback

### CODE REVIEW

**Comment by jonniebigodes** [comment]
with the latest commit the `FrameworkContainer` now has a `flex-wap` added to prevent messing up the layout. If that's not the intended behaviour and the frameworks need to stay in one single line i'll update the pr accordingly.

Feel free to provide feedback

**Comment by domyen** [comment]
This is great @jonniebigodes. I was just about to write a comment about flex-wrap based on what's on production :)

**Comment by jonniebigodes** [comment]
@domyen yes, i forgot about that. I'll add it shortly and commit it.

**Comment by jonniebigodes** [comment]
@domyen there you go, just commited it.

**Comment by domyen** [comment]
Is there a way to convert these names into "display" names.

For instance: 
`react-native` 👉 "React Native"
`ember` 👉 "Ember"

**Comment by jonniebigodes** [comment]
we can capitalize the first letter of each framework sure. Let me just see check something and i'll report back.

**Comment by jonniebigodes** [comment]
@domyen just commited what you wanted. I went with a simple approach. Let me know what you think.

**Comment by domyen** [comment]
Awesome work! Merging now

**Pull request merged**
