### PR TITLE
Spanish Translation "Create an addon"

### PR DESCRIPTION
**Pull request by IvanHatt**
I finished the spanish translation of the chapter "Create an addon"
Please review

Thanks

### CODE REVIEW

**Review by amartinez62 — COMMENTED** [review]
LGTM!! 🎉

**Comment by jonniebigodes** [comment]
@amartinez62 thank you once more for the time you took from your busy schedule to take a look at this pull request. Really appreciate it. @IvanHatt I've checked it as well and nothing stands out. With that, I'm going to merge this pull request. One final thing I would like from you if you're ok. If you could jump onto our [Discord Server](https://discord.gg/UUt2PJb) and message me (same username) to follow up on this pull request.

Sounds good?

Stay safe

**Comment by IvanHatt** [comment]
@jonniebigodes thanks!
The link for Discord Server has expired, can you send me another one?
Have a great day!

**Comment by jonniebigodes** [comment]
@IvanHatt no need to thank! I'll check what could be happening with Discord server link! Could you check if [this one](https://discord.gg/storybook) works for you?

**Pull request merged**
