### PR TITLE
work in progress to address discoverability issue

### PR DESCRIPTION
**Pull request by jonniebigodes**
This pr addresses #270.

This is a work in progress. So far is almost matching the intended changes. There's some styling issues that need to be addressed.

Leaving in the "DO NOT MERGE" label to avoid accidentaly having this merged.

Feel free to provide feedback.

### CODE REVIEW

**Comment by jonniebigodes** [comment]
@domyen and @kylesuss when you're able i would like your feedback on this so that i can proceed from this point.

**Comment by jonniebigodes** [comment]
With the latest commit i've changed the `index.md` in the folder `content\intro-to-storybook` and also the styling a bit as it was long overdue. The circle ci check is continuing to fail at this stage as i have to fix some lint issues. The focus for now is to check if this ok. Once this is validated, the linting issues will be addressed.

Feel free to provide feedback

**Comment by domyen** [comment]
Hey @jonniebigodes thanks you for the PR! 

## Guide landing badges
These should look the same but be clickable. 
image

For the badge hover state let's outline the badges in the same blue border we use for the chapters:
image



## Guide sidebar
What I'm thinking about for the UI: 
image

We can use the standard TooltipLinkList component from the design system to list the available languages for that framework. [Live example](https://storybook-design-system.netlify.com/?path=/story/design-system-tooltip-tooltiplinklist--story-0) and [story code](https://github.com/storybookjs/design-system/blob/master/src/components/tooltip/TooltipLinkList.stories.js)

WDYT?

**Comment by jonniebigodes** [comment]
@domyen thanks for the input and  i'll go over it over the next days. 

> Regarding 
These should look the same but be clickable.

They are to some degree, the text is but not icon.

> For the badge hover state let's outline the badges in the same blue border we use for the chapters:

I left in the current behaviour as a experiment, the border looks better i agree and i'll update shortly.

The tooltip just needs a couple of tweeks and it should match what's intended.


On a side note. Can you get me the ember icon? The hamster with the shades:P! I'm currently going over the ember documentation and trying to match it to the learnstorybook tutorial. And having it would be awesome.

**Comment by domyen** [comment]
Nice and thanks again! 

Here's the [Ember icon](https://github.com/storybookjs/frontpage/blob/master/src/images/logos/framework/icon-ember.svg).

**Comment by jonniebigodes** [comment]
with the latest commit i started to address the feedback provided, While doing this a couple of things popped in my mind:
1- When there's only one version of the tutorial (see svelte version), should the list show the link to the english version and the link to "help translate" or only the link to help translate?
2- Is the `LinkWrapper` needed in this case? Or is only required for adding customization or any other information  to the links? I'm asking this because i'm still getting acquainted with the design system.

**Comment by domyen** [comment]
1. Show English and the Help translate link
2. This is tricky! LinkWrapper is still needed because we're adding internal links to other parts of the Gatsby site, but we need extra logic because the "help us translate" link is external. 

re: 2,
Check out how we do it in the [Header component l228](https://github.com/chromaui/learnstorybook.com/blob/master/src/components/composite/Header.js#L228). Specifically, we have a conditional that checks if it's a Gatsby link. We use that function in a tooltip later on in Header [like this](https://github.com/chromaui/learnstorybook.com/blob/master/src/components/composite/Header.js#L280).

**Comment by jonniebigodes** [comment]
@domyen just updated the component based on the feedback. The same approach was used here as it's used in the header component. A side note, probably in the future the usage of the wrapper could be extracted  to a separate function or something in that nature as it's originating duplication of code. But for now i think that we're getting there.

Feel free to provide feedback

**Comment by domyen** [comment]
@jonniebigodes this looks awesome! Left a comment about adding another story with multiple frameworks and multiple languages to stress test the UI here: https://www.chromaticqa.com/pullrequest?appId=5cf841a3f3e3d200208ffc74&number=277&view=activity

**Comment by jonniebigodes** [comment]
@domyen yes we can and i totally forgot about it. I'll update probably today or tomorrow the latest. So that we can merge this and close the underlying issue.

**Comment by domyen** [comment]
Nice, the new stories are great. 

Can we specify the order of the frameworks from left to right starting with the most to least popular: React, React Native, Vue, Angular, Svelte.

**Comment by jonniebigodes** [comment]
@domyen i just updated the story file with some changes. With that a couple of things popped in my mind that could be already be used to trully battle test this and save time in the future.
1- Would it be a good idea to have the icons for each available framework already available? Currently the most used ones are already added. And per your comment we have the ember one. Probably adding the rest would save us time with the site, content and the storybook.
2- Probably add more languages in the [getLanguageName function](https://github.com/chromaui/learnstorybook.com/blob/master/src/lib/getLanguageName.js) to avoid having a pr to specifically address that. And with that leave the future contributor to any translation focused on the content itself. For now we could probably start the ones proposed in #3


Regarding this:

> Can we specify the order of the frameworks from left to right starting with the most to least popular: React, React Native, Vue, Angular, Svelte.

We could do it probably, for now they are sorted alphabetically. But i would love to hear on you would like to do it. From the top of my mind we could take a look [at](https://2019.stateofjs.com/front-end-frameworks/) and use their numbers? 

Something like that probaby?

**Comment by domyen** [comment]
1. That sounds good and is pretty easy! We can pull the icons over from the storybookjs/frontpage [here](https://github.com/storybookjs/frontpage/tree/master/src/images/logos/framework)
2. That's a good idea 👍 I don't think we need to cover every language, just more of the common ones than we have now.

**Ordering:** I'd like to sort them manually in this case. Storybook adoption in various ecosystems is all over the place. For instance, the Angular framework has been around a lot longer but has much less SB adoption than Vue. My intention is to show the frameworks whose users have adopted Storybook the most from left to right. Currently that is: React, React Native, Vue, Angular, Svelte.

**Comment by jonniebigodes** [comment]
@domyen with the latest commit both items were covered, updated the frameworks and added some extra languages based on the translation issue. Also the stories were updated.

On the topic of ordering i'll do it between tonight and tomorrow. But your comment led me to think one thing, for now we could go with a manual ordering like that. But in the future we can do better. We have a metric in place that could be used to increase exposure based on the frameworks, more specifically the translations. As some need some much desired tlc and with that increase also exposure for Storybook. I'm aware that this is a uphill battle that will last a long time, but we getting there, inch by inch, as per recent prs that were merged. 

Let me know what you think

**Comment by jonniebigodes** [comment]
@domyen sorry for the delay..i had to take care of some stuff around the house. I've just updated the component per feedback.

Feel free to provide feedback

**Comment by jonniebigodes** [comment]
@domyen i'm going to remove the "do not merge" label from this pr. Do you need anything more done? Or are good to go and merge this?

**Comment by domyen** [comment]
Apologies, must've missed the latest commit. Looks good to me!

**Comment by jonniebigodes** [comment]
@domyen if you don't mind i'll merge this shortly. I have to take care of some stuff in my home.

**Pull request merged**
