### PR TITLE
Update architecture.md

### PR DESCRIPTION
**Pull request by raoasifraza11**
spelling errors and fix typo.

### CODE REVIEW

**Comment by raoasifraza11** [comment]
Hi @jonniebigodes there is a pending PR by @JohnBraga45 it seems he is not active form long time [PR](https://github.com/chromaui/learnstorybook.com/pull/678)

**Comment by jonniebigodes** [comment]
@raoasifraza11, thanks for taking the time and effort into this pull request and helping with the translation. I will merge this one and close the other as there's no movement for a long period of time and also as the change would be a small one.

Hope you have a great weekend.

Stay safe

**Comment by raoasifraza11** [comment]
@jonniebigodes thank you for the review.

**Comment by jonniebigodes** [comment]
No need to thank whatsoever. It was my pleasure @raoasifraza11 🙏

**Pull request merged**
