### PR TITLE
Chore: Bump packages versions.

### PR DESCRIPTION
**Pull request by jonniebigodes**
With this pr the packages versions with the exception of formik were updated.

Moving `formik` to the latest version, introduces a bug with not only the stories but also with the site. I haven't pinpointed it yet, so i thought it would be best to leave it in the current version to avoid breaking functionality.

Also contributing to the effort of changing the stories format to csf. As the documentation is being moved, also a good thing would be that learnstorybook's site would benefit from this aswell.

I'm adding the label `DO NOT MERGE` temporarily as this is reviewed in more detail

Feel free to provide feedback

### CODE REVIEW

**Comment by domyen** [comment]
Nice thanks! I approved the changes in Chromatic caused by the slightly changed story names 👍

**Comment by jonniebigodes** [comment]
with the latest commits Storybook was updated to version >=5.3 and the configuration was updated per said version. 

I had to revert back husky to prevent the CI deployment to be stuck on a endless loop of building/failing.

Ran the new version Storybook locally and there's one caveat that should be mentioned. If there's no `.cache` or `public` folder present, it will fail with the following message:

```bash
ERROR in ./src/components/screens/IndexScreen/index.js
Module not found: Error: Can't resolve '..\..\..\..\public\static\d\2833345082.json' in '\storybook_move_to_csf\learnstorybook.com\src\components\screens\IndexScreen'
 @ ./src/components/screens/IndexScreen/index.js 45:0-81 113:10-25
 @ ./src/components/screens/IndexScreen/index.stories.js
 @ ./src/components sync ^\.\/(?:(?:(?!\.)(?:(?:(?!(?:|[\\\/])\.).)*?)[\\\/])?(?!\.)(?=.)[^\\\/]*?\.stories\.js[\\\/]?)$
 @ ./.storybook/generated-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/preview.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=true

ERROR in ./src/components/screens/TeamScreen/index.js
Module not found: Error: Can't resolve '..\..\..\..\public\static\d\3337041852.json' in '\storybook_move_to_csf\learnstorybook.com\src\components\screens\TeamScreen'
 @ ./src/components/screens/TeamScreen/index.js 35:0-81 99:10-25
 @ ./src/components/screens/TeamScreen/index.stories.js
 @ ./src/components sync ^\.\/(?:(?:(?!\.)(?:(?:(?!(?:|[\\\/])\.).)*?)[\\\/])?(?!\.)(?=.)[^\\\/]*?\.stories\.js[\\\/]?)$
 @ ./.storybook/generated-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/preview.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=true

ERROR in ./src/components/composite/AppLayout.js
Module not found: Error: Can't resolve '..\..\..\public\static\d\2144662441.json' in '\storybook_move_to_csf\learnstorybook.com\src\components\composite'
 @ ./src/components/composite/AppLayout.js 1:0-77 75:10-25
 @ ./src/components/composite/AppLayout.stories.js
 @ ./src/components sync ^\.\/(?:(?:(?!\.)(?:(?:(?!(?:|[\\\/])\.).)*?)[\\\/])?(?!\.)(?=.)[^\\\/]*?\.stories\.js[\\\/]?)$
 @ ./.storybook/generated-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/preview.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=true
```
I'm assuming that as there's some Gatsby static queries present in the components, then the data needs to be present before Storybook can be started. I was able to circumvent it by issuing `gatsby develop` or even `gatsby build` and then "fire up" Storybook and all worked out fine.


Also i'm seeing one thing when running it locally, i haven't checked the preview deploy but the same behaviour should be also present.

When i ran a local production build and served it, opening up `http://localhost:9000` and looking at the layout it seems a bit weird, the links look and feel seems odd. As you can see below:
storybook_update_deps_chrome_chrome_edge
storybook_update_deps_firefox


@kylesuss i'm pinging you as you're directly involved site revamp and design system implementation. If you don't mind taking a look at it? And if the issue is not on your end, but either with Gatsby or Styled components i'll revert back the packages version.

@domyen sorry for probably spamming you with some mails, triggered by the build failure. I think everything should be ok in that department. And regarding the stories name choosing i tried to make  the closest possible to the original. Thank you for approving it Chromatic

**Comment by kylesuss** [comment]
@jonniebigodes thanks for the callout. Yeah the deploy preview looks off but I'm not sure why yet. I just pulled this branch down locally and ran `yarn dev` but am not seeing an issue when I do that -- are you? Was the issue for you only when building for production locally?

**Comment by kylesuss** [comment]
@jonniebigodes ok yes I answered my own question -- it seems like it only happens w/ the prod build. I have at the very least tracked it down to the `styled-components` upgrade. When I set that package back to the old version, the problem goes away..

**Comment by kylesuss** [comment]
Ok @jonniebigodes the problem w/ styling is fixed. I had to upgrade `styled-components` in the `design-system` as I noticed we had 2 versions of the lib being loaded.

I think we may make `styled-components` a peer dep in the design system eventually, but right now that is not the case.

**Comment by jonniebigodes** [comment]
@kylesuss that was my reasoning aswell. it seems that during the new releases of Styled Components it breaks the layout. I'll revert back the package tomorrow, test it locally and commit it. If you don't mind me bothering you again. But can you at pinpoint me to the where the navigation components are and also the logic for it? To add a little more context, as you have the branch already in your machine, if you run `gatsby develop` and go through any of the tutorials that don't have the create addons section, as soon as you reach the deployment section, you go through it and when you reach the end of it, the link is pointing to an incorrect section, instead of pointing to the conclusion, it's pointing to the contribute section. This is a bit of a break of functionality don't you think? I don't mind going over this as i'm currently working on it.

**Comment by kylesuss** [comment]
@jonniebigodes I already fixed & committed the design system package update here:

https://github.com/chromaui/learnstorybook.com/pull/246/commits/a47cc8a4ff40fb38b22735cd67d0ab19fb636a69

As for the navigation, I think what you describe might be a problem already on the live site. The way the navigation is built, there is an assumption that every guide will have the same chapters in each language which may be causing the problem right now.

I just put up this PR which fixes a navigation issue for what I have described:

https://github.com/chromaui/learnstorybook.com/pull/259

Mind taking a look and seeing if that is the same problem you describe?

**Comment by jonniebigodes** [comment]
@kylesuss i've pulled in the updated design system package and took a quick look locally and it seems that the issue is solved. It was just committed, i'll check the pr you mentioned, regarding the navigation in a bit

**Comment by jonniebigodes** [comment]
i'm going to close this out and wait for Storybook 6.0 to land as it will be more beneficial in terms of configuration and so on. I've been doing some research and found out that with the current Storybook beta and hopefully the release some parts of the gatsby config will be further streamlined and reduce the boilerplate code needed to get the two frameworks working properly.

**Pull request closed without merging**
