### PR TITLE
Import should be PureTaskList

### PR DESCRIPTION
**Pull request by catenare**
This file import TaskList but in the previous chapter, we created the PureTaskList component.

### CODE REVIEW

**Comment by tmeasday** [comment]
Hi @catenare  - the `TaskList` is a wrapper around the `PureTaskList` that supplies it with real data. This is intentional, I think?

**Comment by jonniebigodes** [comment]
@catenare, what @tmeasday says it's correct the `TaskList` import is acting up as a wrapper and if you both don't mind there's room for improvement here, we can do better and improve the documentation to prevent  misleadings. If you're both ok with this tomorrow (monday) i'll update my version of the tutorial's code based on react and come back a more in depth comment and we proceed from there. Sounds good to both of you?

**Comment by jonniebigodes** [comment]
@catenare sorry for the delay but i was sidetracked, i was going over this and like i said we have room for a possible improvement in the documentation. My idea was to "take a page" (pardon the bad pun) from the vue documentation more specifically starting at the [data](https://www.learnstorybook.com/intro-to-storybook/vue/en/data/) section and then to the next section, the [screen](https://www.learnstorybook.com/intro-to-storybook/vue/en/screen/). The reasoning behind this is the following, by making this change to the documentation we are preventing misleadings that a reader might have. Like you've probably have, hence the reason of this pr. Also we have to be aware that not everyone has knowledge of React/Redux and by introducing a similar code base and flow to this version of the tutorial we also lower the entry barrier a bit, i'm perfectly aware that the scope of the tutorial is not Redux, but if in the process we inform people how to quickly setup redux in a React app i personally believe it's a win.  And finally with this change he'll have something to be displayed as soon as possible. He/she won't have to wait for the next section for some something tangible.

My question to you is the following, are you willing to work on these changes?

And my question to both @tmeasday and @domyen is the following, are you both ok with the change? 

I have the codebase used for this almost done and commented out, if you're up for it i can push it to a repo in here and help you with this.

Feel free to provide feedback

**Comment by catenare** [comment]
Would like to work on the changes. Let me take a look.

**Comment by jonniebigodes** [comment]
@catenare wow..that's fantastic. I'll push the code to github a bit later today so that you can take a look at it, as soon as it's available i'll let you know.

**Comment by tmeasday** [comment]
@jonniebigodes sorry for the delay here.

I'm not completely sure what you mean by taking the approach of the Vue data/screens pages in the React version.

As far as I can tell they take a very similar approach already, but I'm probably missing something crucial. Can you explain to me what's different?

**Comment by jonniebigodes** [comment]
@catenare sorry for the late response, but yesterday i was still a bit "under the weather" i thought the bad cold i had the past week was already flushed out of my system, but i was wrong...i completely passed out. And with that forgot to push the code for the repo. without further ado [here](https://github.com/jonniebigodes/intro_storybook_for_pr_278) it is.

Key things to look for:

- `src\App.js`- the code is documented and while you take a look at the vue version you'll see what i mean.
- `src\components`- once again the code is documentated per stage and once again while you take a look at the code and the vue version, you'll see what i mean.

@tmeasday sorry for not being more clearer in my comment. Note to self...avoid writing when a bit feverish. 

On to the topic at hand. What i meant to say was with taking the approach like Vue version it will lower the entry barrier to the reader. I know the scope of the tutorial is not to teach Redux, but if we can offer a simple way to setup it up i think it's a bonus.  

The way the tutorial is setup now, it might seem a bit confusing to a newcomer how all the pieces fit together. Hence the pr that stemmed this conversation.

Taking the vue approach will offer a clearer picture of what is happening at each stage. It means adding a couple more components and extending both sections a bit, me personally i'm ok with it if it will improve the documentation and helps out the reader. 

For the seasoned developer that is confortable with Redux, he will know what is happening and probably go the route the tutorial is currently setup or other similar route.

**Comment by tmeasday** [comment]
@jonniebigodes I guess I'll wait and see what the PR looks like ;)

**Comment by jonniebigodes** [comment]
@catenare as a added bonus, if you take a look at the [react native data](https://www.learnstorybook.com/intro-to-storybook/react-native/en/data/) and the [React Native screen](https://www.learnstorybook.com/intro-to-storybook/react-native/en/screen/) sections they already have the wording in place, the codebase could probably be a bit more familiar to the react one that i mentioned. If you don't mind, take a look at it.

**Comment by jonniebigodes** [comment]
@catenare hope you don't mind, but i'm going to close this pull request. With the recent changes introduced in the documentation in #363 we addressed the underlying issue. It goes without saying, thank you very much for the time and effort you took in creating it and sorry for taking so long in addressing it. But it's been a bit of a busy months.

Hope you're doing good and staying safe.

**Pull request closed without merging**
