### PR TITLE
Update simple-component.md

### PR DESCRIPTION
**Pull request by Woodii1998**
Fixing typos

### CODE REVIEW

**Comment by jonniebigodes** [comment]
@Woodii1998 thanks for taking the time and effort in putting this pull request together and helping us improve the translation by fixing some typos, we appreciate it 🙏 

I was wondering if you're willing to continue working on this pull request and update the whole translation as it's quite outdated.

Let me know and we'll go from there. 

Hope you have a great week.

Stay safe

**Comment by Woodii1998** [comment]
@jonniebigodes I'm sorry I just saw your reply, I can help update the Chinese document, I'm usually busy, so it may take some time, and I need to start my work from where?

**Comment by jonniebigodes** [comment]
@Woodii1998, no need to apologize whatsoever. I understand completely, and if you're ok with it, I would suggest the following:
- Close this pull request
- Clone this repo locally
- Create a branch for the incoming translation
- Make the updates based on the [English](https://storybook.js.org/tutorials/intro-to-storybook/react/en/get-started/) version as it's the most current version of the tutorial
- Create a pull request and let me know so that I can follow up with the community for a proofreader (If you know anyone who's willing to help you proofread it would be great).


What do you think? Are you ok with this workflow?

**Comment by Woodii1998** [comment]
Okay, I'll get started on that.

**Comment by Woodii1998** [comment]
@jonniebigodes

**Pull request closed without merging**
