### PR TITLE
Update official addons page link in using addons chapter

### PR DESCRIPTION
**Pull request by supercoder123**
The link is present in the using addons chapter
Link: https://www.learnstorybook.com/intro-to-storybook/react/en/using-addons/

### CODE REVIEW

**Comment by domyen** [comment]
Thank you @supercoder123

**Comment by jonniebigodes** [comment]
@supercoder123 indeed, thank you for the small, but rather important contribution. Like @domyen mentioned if you could replace the url globally would mean a lot. Let me know once you have it and i'll be more than happy to merge this pull request.

Sounds good?

Stay safe

**Comment by supercoder123** [comment]
Sure will replace it everywhere

**Comment by supercoder123** [comment]
Done

**Comment by jonniebigodes** [comment]
@supercoder123 just checked and we are good to go. I'll merge this in a bit. I have a couple of tasks to take care of.

Once again and it goes without saying, thank you very much for the time and effort you put into the pull request.

Stay safe.

**Pull request merged**
