### PR TITLE
update the chapter of “deploy” of zh-TW

### PR DESCRIPTION
**Pull request by linyiru**
1. replace `npm` with `yarn` because I found the latest version in English use `yarn`
2. use more specific terms for better reading experience for users who reads Traditional Chinese.

### CODE REVIEW

**Comment by jonniebigodes** [comment]
@linyiru thank you for the time and contribution to the documentation. But and if you're willing it would be best to update the entire translation as it's in dire need of some tlc (pardon the bad pun). Then we can reach out to the community and fine tune it so that it's up to par. Me personally and i believe the  rest of the team would appreciate the effort.

**Comment by linyiru** [comment]
@jonniebigodes good idea. 

I'll try to make it recently, you're right that will very good to reach out to the community. Thank you

**Comment by jonniebigodes** [comment]
@linyiru per your comment i see that you're willing to make the effort to update the translation and that's really nice, thank you very much in advance for the time and effort you'll be putting into this. If you don't mind, I'm going to put the label "do not merge" as to avoid this getting merged accidently while you work on the translation. As normally when it comes to documentation the team prefers to have the complete tutorial in one pr to make it more easy to go over and fine tune. Also when you're able rename your pull request and when you'll have the complete tutorial done i'll remove the label and we can go from there. Sounds good?

**Comment by linyiru** [comment]
@jonniebigodes sure. no problem I'll update my PR soon and thanks for your help to make it better.

**Comment by jonniebigodes** [comment]
@linyiru just a heads up. I'm closing this in favor of #441. If you're ok we'd love for your contribution in this case more of a proofreader than an actual translator. If you could help out @ymcheung we'd really appreciate it to get the pull request merged.

Stay safe

**Pull request closed without merging**
